version: 2

jobs:
  install:
    docker:
      - image: circleci/node:8.6.0

    steps:
      - checkout

      - restore_cache:
          key: grunt-and-bower
      - run:
          name: Install grunt and bower
          command: yarn global add bower grunt-cli
      - save_cache:
          key: grunt-and-bower
          paths:
            - ~/.config/yarn/global

      - restore_cache:
          key: bower-deps-{{ checksum "bower.json" }}
      - run:
          name: Install bower deps
          command: npx bower i
      - save_cache:
          key: bower-deps-{{ checksum "bower.json" }}
          paths:
            - bower_components

      - restore_cache:
          key: v2-node8-yarn-deps-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Node dependencies
          command: |
            if [ ! -d ./node_modules ]; then
              yarn --pure-lockfile
            fi
      - save_cache:
          key: v2-node8-yarn-deps-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Build modernizr
          command: npx grunt modernizr:dist
      - save_cache:
          key: modernizr-{{ .Revision }}
          paths:
            - vendor/modernizr/modernizr-build.js

  test:
    docker:
      - image: circleci/node:8.6.0-browsers
        environment:
          JOBS: 2

    steps:
      - checkout
      - restore_cache:
          key: bower-deps-{{ checksum "bower.json" }}
      - restore_cache:
          key: v2-node8-yarn-deps-{{ arch }}-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: modernizr-{{ .Revision }}
      - run:
          name: Test
          environment:
            CIRCLE_TEST_REPORTS: test-results
          command: npx ember test
      - store_test_results:
          path: test-results/

  deploy_production:
    docker:
      - image: circleci/node:8.6.0
        environment:
          JOBS: 2
    steps:
      - checkout
      - restore_cache:
          key: bower-deps-{{ checksum "bower.json" }}
      - restore_cache:
          key: v2-node8-yarn-deps-{{ arch }}-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: modernizr-{{ .Revision }}
      - run:
          name: Deploy to production
          command: |
            env | sed -n 's/^DEPLOY_//p' > .env
            env | sed -n 's/^PROD_//p' >> .env
            npx ember deploy production --verbose --activate

  deploy_demo:
    docker:
      - image: circleci/node:8.6.0
        environment:
          JOBS: 2
    steps:
      - checkout
      - restore_cache:
          key: bower-deps-{{ checksum "bower.json" }}
      - restore_cache:
          key: v2-node8-yarn-deps-{{ arch }}-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: modernizr-{{ .Revision }}
      - run:
          name: Deploy to demo
          command: |
            env | sed -n 's/^DEPLOY_//p' > .env
            env | sed -n 's/^DEMO_//p' >> .env
            npx ember deploy demo --verbose --activate

  deploy_qa:
    docker:
      - image: circleci/node:8.6.0
        environment:
          JOBS: 2
    steps:
      - checkout
      - restore_cache:
          key: bower-deps-{{ checksum "bower.json" }}
      - restore_cache:
          key: v2-node8-yarn-deps-{{ arch }}-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: modernizr-{{ .Revision }}
      - run:
          name: Deploy QA build
          command: |
            env | sed -n 's/^DEPLOY_//p' > .env
            env | sed -n 's/^PROD_//p' >> .env
            npx ember deploy qa:$CIRCLE_BRANCH --verbose --activate

workflows:
  version: 2
  install-test-deploy:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
          requires:
            - install
      - deploy_production:
          requires:
            - test
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
      - deploy_demo:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy_qa:
          requires:
            - test
          filters:
            branches:
              only: /(feature\/.+)|([a-zA-Z]+-\d+)/
